version: '3.8'
services:

  postgres:
    image: postgres:15.1
    restart: always
    environment:
      - POSTGRES_USER=usermanagement
      - POSTGRES_PASSWORD=usermanagementpw
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres: